mysite/autoservice/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('vehicles/', views.vehicles, name="vehicles"),
    path('vehicles/<int:vehicle_id>', views.vehicle, name='vehicle'),
    path('search/', views.search, name='search'),
    path('myorders/', views.MyOrderListView.as_view(), name = 'myorders'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>', views.OrderDetailView.as_view(), name="order"),
    path('orders/new', views.OrderCreateView.as_view(), name='order_new'),
    path('orders/<int:pk>/update', views.OrderUpdateView.as_view(), name='order_update'),
    path('orderes/<int:pk>/delete', views.OrderDeleteView.as_view(), name='order_delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='autoservice/', permanent=True)),
    path('autoservice/', include('autoservice.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

mysite/autoservice/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
import pytz

utc = pytz.UTC
from tinymce.models import HTMLField
from PIL import Image


# Create your models here.
class VehicleModel(models.Model):
    make = models.CharField(verbose_name="Gamintojas", max_length=50)
    model = models.CharField(verbose_name="Modelis", max_length=50)

    def __str__(self):
        return f"{self.make} {self.model}"

    class Meta:  # Modeliu pavadinimai yra atvaizduojami teisingai vienaskaita ir daugiskaita (Autoservice skiltyje ir iejus i vidu)
        verbose_name = "Automobilio modelis"
        verbose_name_plural = "Automobilio modeliai"


class Service(models.Model):
    name = models.CharField(verbose_name="Pavadinimas", max_length=50)
    price = models.IntegerField(verbose_name="Kaina")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Paslauga"  # Modeliu pavadinimai yra atvaizduojami teisingai vienaskaita ir daugiskaita (Autoservice skiltyje ir iejus i vidu)
        verbose_name_plural = "Paslaugos"


class Vehicle(models.Model):
    plate = models.CharField(verbose_name="Valstybinis numeris", max_length=6)
    vin = models.CharField(verbose_name="VIN kodas", max_length=17)
    owner_name = models.CharField(verbose_name="Savininkas", max_length=50)
    vehicle_model = models.ForeignKey(to="VehicleModel", verbose_name="Automobilio modelis", on_delete=models.SET_NULL,
                                      null=True)
    photo = models.ImageField(verbose_name='Nuotrauka', upload_to="vehicles", null=True, blank=True)
    description = HTMLField(verbose_name="Aprasymas", null=True, blank=True)

    def __str__(self):
        return f"{self.vehicle_model} ({self.plate})"

    class Meta:  # Modeliu pavadinimai yra atvaizduojami teisingai vienaskaita ir daugiskaita (Autoservice skiltyje ir iejus i vidu)
        verbose_name = "Automobilis"
        verbose_name_plural = "Automobiliai"


class Order(models.Model):
    date = models.DateTimeField(verbose_name="Data", auto_now_add=True)
    client = models.ForeignKey(to=User, verbose_name="Klientas", on_delete=models.SET_NULL, null=True, blank=True)
    vehicle = models.ForeignKey(to="Vehicle", verbose_name="Automobilis", on_delete=models.SET, null=True)
    deadline = models.DateTimeField(verbose_name="Terminas", null=True, blank=True)

    def deadline_overdue(self):
        return self.deadline and datetime.datetime.today().replace(tzinfo=utc) > self.deadline.replace(tzinfo=utc)

    def total(self):
        total_sum = 0
        for line in self.lines.all():
            total_sum += line.sum()
        return total_sum

    def __str__(self):
        return f"{self.vehicle} ({self.date})"

    LOAN_STATUS = (  # migracijas reikia pasidaryti nes kitaip klaida mes
        ('p', 'Patvirtinta'),
        ('v', 'Vykdoma'),
        ('a', 'Atsaukta'),
        ('t', 'Tvirtinama'),
        ('i', 'Ivykdita'),
    )

    status = models.CharField(verbose_name="Busena", max_length=1, choices=LOAN_STATUS, blank=True, default='t')


class Meta:  # Modeliu pavadinimai yra atvaizduojami teisingai vienaskaita ir daugiskaita (Autoservice skiltyje ir iejus i vidu)
    verbose_name = "Uzsakymas"
    verbose_name_plural = "Uzsakymai"
    ordering = ['-id']


class Order_line(models.Model):
    order = models.ForeignKey(to="Order", on_delete=models.CASCADE, related_name="lines")
    service = models.ForeignKey(to="Service", verbose_name="Paslauga", on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(verbose_name="Kiekis")

    def sum(self):
        return self.service.price * self.quantity

    def __str__(self):
        return f"{self.order.vehicle} ({self.order.date}) : {self.service} - {self.quantity} "

    class Meta:
        verbose_name = "Uzsakymo eilute "  # Modeliu pavadinimai yra atvaizduojami teisingai vienaskaita ir daugiskaita (Autoservice skiltyje ir iejus i vidu)
        verbose_name_plural = "Uzsakymo eilutes"


class OrderComment(models.Model):
    order = models.ForeignKey(to="Order", on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(to=User, verbose_name="Autorius", on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(verbose_name="Data", auto_now_add=True)
    content = models.TextField(verbose_name='Tekstas', max_length=5000)

    class Meta:
        verbose_name = "Komentaras"
        verbose_name_plural = 'Komentarai'
        ordering = ['-date_created']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.photo.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photo.path)

mysite/autoservice/forms.py
from .models import OrderComment, Profile, Order
from django import forms
from django.contrib.auth.models import User


class OrderCommentForm(forms.ModelForm):
    class Meta:
        model = OrderComment
        fields = ["content"]


class UserUpdateForm(forms.ModelForm):
    # email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']


class MyDateTimeInput(forms.DateInput):
    input_type = 'datetime-local'


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['vehicle', 'deadline', 'status']
        widgets = {'deadline': MyDateTimeInput()}

mysite/autoservice/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Service, Order, Vehicle
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.views.generic.edit import FormMixin
from .forms import OrderCommentForm, UserUpdateForm, ProfileUpdateForm, OrderForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin


def search(request):
    query = request.GET.get('query')
    search_results = Vehicle.objects.filter(
        Q(plate__icontains=query) | Q(vin__icontains=query) | Q(owner_name__icontains=query) | Q(
            vehicle_model__make__icontains=query) | Q(vehicle_model__model__icontains=query))
    return render(request, 'search.html', {'vehicles': search_results, 'query': query})


# Create your views here.
def index(request):
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    context = {
        "service_count": Service.objects.count(),
        "orders_done": Order.objects.filter(status__exact="i").count(),
        "vehicles": Vehicle.objects.count(),
        'num_visits': num_visits,

    }
    return render(request, 'index.html', context=context)


def vehicles(request):
    paginator = Paginator(Vehicle.objects.all(), 2)
    page_number = request.GET.get('page')
    paged_vehicles = paginator.get_page(page_number)
    context = {
        "vehicles": paged_vehicles,
    }
    return render(request, "vehicles.html", context=context)


def vehicle(request, vehicle_id):
    context = {
        "vehicle": get_object_or_404(Vehicle, pk=vehicle_id)
    }
    return render(request, 'vehicle.html', context=context)


class MyOrderListView(generic.ListView):
    model = Order
    template_name = 'my_orders.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(client=self.request.user)


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'registration/register.html')


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.info(request, f"Profilis atnaujintas")
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)


class OrderListView(generic.ListView):
    model = Order
    template_name = 'orders.html'
    context_object_name = 'orders'
    paginate_by = 2


class OrderDetailView(FormMixin, generic.DetailView):
    model = Order
    template_name = 'order.html'
    context_object_name = 'order'
    form_class = OrderCommentForm

    def get_success_url(self):
        return reverse('order', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.order = self.object
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class OrderCreateView(LoginRequiredMixin, generic.CreateView):
    model = Order
    # fields = ['vehicle', 'deadline', 'status']
    success_url = "/autoservice/orders/"
    template_name = 'order_form.html'
    form_class = OrderForm

    def form_valid(self, form):
        form.instance.client = self.request.user
        return super().form_valid(form)


class OrderUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Order
    # fields = ['vehicle', 'deadline', 'status']
    # success_url = "/autoservice/orders/"
    template_name = 'order_form.html'
    form_class = OrderForm

    def get_success_url(self):
        return reverse('order', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        form.instance.client = self.request.user
        return super().form_valid(form)

    def test_func(self):
        return self.get_object().client == self.request.user


class OrderDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Order
    context_object_name = 'order'
    template_name = 'order_delete.html'
    success_url = "/autoservice/orders/"

    def test_func(self):
        return self.get_object().client == self.request.user

mysite/autoservice/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block "title" %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Add additional CSS in static file -->
    {% load static %}
    <!--  <link rel="stylesheet" href="{% static 'css/styles.css' %}">-->
</head>
<body>
{% load i18n %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor" class="bi bi-car-front"
                 viewBox="0 0 16 16">
                <path d="M4 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm10 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM6 8a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2H6ZM4.862 4.276 3.906 6.19a.51.51 0 0 0 .497.731c.91-.073 2.35-.17 3.597-.17 1.247 0 2.688.097 3.597.17a.51.51 0 0 0 .497-.731l-.956-1.913A.5.5 0 0 0 10.691 4H5.309a.5.5 0 0 0-.447.276Z"/>
                <path d="M2.52 3.515A2.5 2.5 0 0 1 4.82 2h6.362c1 0 1.904.596 2.298 1.515l.792 1.848c.075.175.21.319.38.404.5.25.855.715.965 1.262l.335 1.679c.033.161.049.325.049.49v.413c0 .814-.39 1.543-1 1.997V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.338c-1.292.048-2.745.088-4 .088s-2.708-.04-4-.088V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.892c-.61-.454-1-1.183-1-1.997v-.413a2.5 2.5 0 0 1 .049-.49l.335-1.68c.11-.546.465-1.012.964-1.261a.807.807 0 0 0 .381-.404l.792-1.848ZM4.82 3a1.5 1.5 0 0 0-1.379.91l-.792 1.847a1.8 1.8 0 0 1-.853.904.807.807 0 0 0-.43.564L1.03 8.904a1.5 1.5 0 0 0-.03.294v.413c0 .796.62 1.448 1.408 1.484 1.555.07 3.786.155 5.592.155 1.806 0 4.037-.084 5.592-.155A1.479 1.479 0 0 0 15 9.611v-.413c0-.099-.01-.197-.03-.294l-.335-1.68a.807.807 0 0 0-.43-.563 1.807 1.807 0 0 1-.853-.904l-.792-1.848A1.5 1.5 0 0 0 11.18 3H4.82Z"/>
            </svg>
            Autoservisas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Pradzia</a>
                <li/>
                <li>
                    <a class="nav-link" href="{% url 'vehicles' %}">Automobiliai</a>
                <li/>
                <li>
                    <a class="nav-link" href="{% url 'orders' %}">Uzsakymai</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">
                    <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                              clip-rule="evenodd"/>
                    </svg>
                    {{ user.get_username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'myorders' %}">Mano uzsakymai</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'order_new' %}">Naujas uzsakymai</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Atsijungti</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Registruotis</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Prisijungti</a></li>
                {% endif %}
                <li>
                    <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                        <input name="query" class="form-control" type="text" placeholder="Paieška">
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}"
         role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}


    {% block "content" %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
</html>

mysite/autoservice/templates/index.html
{% extends "base.html" %}

{% block title %} Pradzia {% endblock %}

{% block "content" %}

<h1>Autoserviso statistika:</h1>
<ul>
    <li><strong>Paslaugu kiekis: </strong>{{ service_count }}</li>
    <li><strong>Pataisytu automobiliu: </strong>{{ orders_done }}</li>
    <li><strong>Aptarnaujami automobiliai: </strong>{{ vehicles }}</li>
</ul>
<p>Čia jūs lankotes {{ num_visits }}-ą kartą.</p>
{% endblock %}

mysite/autoservice/templates/my_orders.html
{% extends "base.html" %}

{% block "title" %}Mano užsakymai{% endblock %}

{% block "content" %}
<h1>Užsakymai:</h1>
<br>
{% for order in orders %}
<p><a href="{% url 'order' order.pk %}">{{ order.vehicle }}</a> <span class="{% if order.deadline_overdue %}text-danger{% endif %}">({{ order.deadline }})</span></p>
<hr>
{% endfor %}
{% endblock %}

mysite/autoservice/templates/order.html
{% extends "base.html" %}

{% block "title" %} Uzsakymas {% endblock %}

{% block "content" %}
<h1>Uzsakymas:</h1>
<br>

<p><strong>Data: </strong>{{ order.date }}</p>
<p><strong>Automobilis: </strong>{{ order.vehicle }}</p>
<p><strong>Busena : </strong>{{ order.get_status_display }}</p>
<p><strong>Klientas : </strong>{{ order.client }}</p>
{% if order.client == user %}
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'order_update' order.id %}">Redaguoti</a>
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'order_delete' order.id %}">Ištrinti</a>
</div>
{% endif %}
<hr>
<table class="table table-dark table-striped">
    <tr>
        <th>Paslauga</th>
        <th>Kaina</th>
        <th>Kiekis</th>
        <th>Suma</th>
    </tr>
    {% for line in order.lines.all %}
    <tr>
        <td>{{ line.service }}</td>
        <td>{{ line.service.price }}</td>
        <td>{{ line.quantity }}</td>
        <td>{{ line.sum }}</td>
    </tr>
    <!--<p>{{ line }} </p>-->
    {% endfor %}
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>{{ order.total }}</strong></td>
    </tr>
</table>
<h2>Atsiliepimai</h2>
{% if user.is_authenticated %}
<div class="fieldWrapper">
    <hr>
    <br/>
    <h4>Palikite atsiliepimą:</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.content }}</br>
        <input type="submit" value="Paskelbti">
    </form>
</div>
{% endif %}
{% if order.comments.all %}
{% for comment in order.comments.all %}
<hr>
<strong>{{ comment.user }}</strong>, <em>{{ comment.date_created}}</em>
<p>{{ comment.content }}</p>
{% endfor %}
{% else %}
<p>Komentarų nėra</p>
{% endif %}
{% endblock %}

mysite/autoservice/templates/order_delete.html
{% extends "base.html" %}
{% block "title %} Uzsakymo trynimas {% endblock %}
{% block "content" %}
    <div class="content-section">
    <form method="POST">
        {% load crispy_forms_tags %}
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti uzsakyma</legend>
            <h2>Ar tikrai norite ištrinti uzsakyma {{ order }}?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'order' order.id %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock %}

mysite/autoservice/templates/order_form.html
{% extends "base.html" %}

{% block "title" %} Uzsakymo kurimas/redagavimas {% endblock %}

{% block "content" %}
<div class="content-section">
    <form method="POST">
        {% load crispy_forms_tags %}
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Uzsakymo kurimas/redagavimas</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
</div>
{% endblock %}

mysite/autoservice/templates/orders.html
{% extends "base.html" %}

{% block "title" %}Uzsakymai{% endblock %}

{% block "content" %}
<h1>Uzsakymai:</h1>
<br>
{% for order in orders %}
<p><a href="{% url 'order' order.pk %}">{{ order.vehicle }}</a> <span class="{% if order.deadline_overdue %}text-danger{% endif %}">({{ order.deadline }})</span></p>
<img class="rounded-circle" src="{{order.client.profile.photo.url}}">
<p>{{ order.client.username }}</p>
<hr>
{% endfor %}
  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

mysite/autoservice/templates/profile.html
{% extends "base.html" %}

{% block "title" %} Profilis {% endblock %}

{% block "content" %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.photo.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
             <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
                 {% load crispy_forms_tags %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock %}

mysite/autoservice/templates/search.html
{% extends "base.html" %}
{% block "title" %} Paieska {% endblock %}
{% block "content" %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if vehicles %}
  <ul>
    {% for vehicle in vehicles %}
      <li>
        <a href="{% url 'vehicle' vehicle.id %}">{{ vehicle.vehicle_model }}</a> ({{ vehicle.plate }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}